variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprrepexpfacade'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprrepexpfacaderepository'
  serviceName: 'PRDRWDWEBWA1417'