variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: docker.imageName
  value: 'eprrepexpfacade'
- name: acr.azureContainerRegistryName
  value: 'prdrwdinfac1401'
- name: acr.repositoryName
  value: 'eprrepexpfacaderepository'
- name: serviceName
  value: 'PRDRWDWEBWA1417'